// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knkpstbiqfsitpvebund.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtua3BzdGJpcWZzaXRwdmVidW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjgwNzMsImV4cCI6MjA2NDU0NDA3M30.6SULsuCILCOTOCzJPr8HvnlAV9w3pfchaFC9GJvrTaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);